[workspace]
resolver = "2"

members = [
    "examples/dev",
    "examples/flex", "examples/textview", "examples/multithread", "examples/conditional", "examples/scroll",
    "quarve",
    "quarve_cli", "quarve_derive"]
