[package]
name = "quarve_derive"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/monocurl/quarve"
description = "Procedural macros for quarve"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "2.0"
proc-macro-crate = "3.1.0"
